name: CI Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "README.md"

concurrency:
  group: "${{ github.workflow }} @ ${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

env:
  RUST_VERSION: 1.81.0
  CARGO_TERM_COLOR: always

jobs:
  format-and-clippy:
    uses: ./.github/workflows/format-workflow.yaml
    secrets: inherit
  tests:
    uses: ./.github/workflows/tests-workflow.yaml
    secrets: inherit
  build:
    runs-on: ubuntu-latest
    needs: [format-and-clippy, tests]
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: "library"
            path: "."
          - name: "client"
            path: "snap-kube-client"
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
          toolchain: ${{ env.RUST_VERSION }}
      - name: Cargo Build ${{ matrix.name }}
        run: cargo build --verbose
        working-directory: ${{ matrix.path }}
