name: Format & Clippy Pipeline

on:
  workflow_call:

env:
  RUST_VERSION: 1.81.0

jobs:
  format-and-clippy:
    name: Cargo format & Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
          toolchain: ${{ env.RUST_VERSION }}
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
      - name: Lint with Clippy
        run: cargo clippy --all
