name: Tests Pipeline

on:
  workflow_call:

env:
  RUST_VERSION: 1.81.0

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
          toolchain: ${{ env.RUST_VERSION }}
      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-nextest
      - name: Run tests
        run: cargo nextest run --all
